// src/lib/elements/Book.svelte
<section class="section">
    <div class="containter">
        <div class="content is-size-2">
            My book
            <a href="https://sanicbook.com">
                Python Web Development with Sanic
            </a>
            now available
        </div>
    </div>
</section>

<style>
    .section {
        background-color: #ff0d68;
        color: #000000;
        position: relative;
        transform: translateY(-100%);
    }
    .section a {
        color: #000000;
        font-weight: 700;
        text-decoration: underline;
    }
    .section a:hover {
        color: #111111;
    }
    @media (max-width: 800px) {
        .section {
            transform: translateY(-100vh);
            padding: 0.25rem !important;
        }
        .is-size-2 {
            font-size: 1.25rem !important;
        }
    }
</style>

// blog/.vuepress/custom/elements/Book.vue
<template>
  <section class="book">
    My book
    <a href="https://sanicbook.com">Python Web Development with Sanic</a>
    now available
  </section>
</template>

<style scoped>
.book {
  background-color: #ff0d68;
  color: #000000;
  position: absolute;
  bottom: 0;
  width: 100%;
  padding: 3rem;
  font-size: 3rem;
}
.book a {
  color: #000000;
  font-weight: 700;
  text-decoration: underline;
}
.book a:hover {
  color: #111111;
  text-decoration: none;
}
@media (max-width: 800px) {
  .book {
    top: 0;
    bottom: initial;
  }
}
</style>
